# Generated by Django 2.2.17 on 2021-03-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
