# Generated by Django 2.2.17 on 2021-04-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingTime', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='BookId',
        ),
        migrations.AddField(
            model_name='contact',
            name='BookID',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
