# Generated by Django 2.2.17 on 2021-04-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingTime', '0003_auto_20210404_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='uploadImage',
            new_name='UploadImage',
        ),
    ]
