# Generated by Django 2.2.17 on 2021-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingTime', '0005_auto_20210404_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='UploadImage',
            field=models.ImageField(upload_to='ContactImg'),
        ),
    ]
